add_library(nestegg INTERFACE IMPORTED)
set_target_properties(nestegg PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/include"
    INTERFACE_LINK_DIRECTORIES "${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/lib"
    INTERFACE_LINK_LIBRARIES "nestegg"
)
